[job]
dump_folder = "./outputs"
description = "codex tuning"
print_args = true

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_wandb = true

[model]
name = "codex"
flavor = "small"
hf_assets_path = "./assets/hf/Llama-3.1-8B"
converters = []
tokenizer_name = "gpt2"
tokenizer_path = ""
ffn_scale = 1.0

[optimizer]
name = "AdamW"
lr = 6e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 5  # lr scheduler warm up

[training]
local_batch_size = 4
seq_len = 1024
max_norm = 1.0  # grad norm clipping
steps = 10
dataset = "c4_test"
dataset_path = "torchtitan/tests/assets/c4_test"
log_activations = true

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
pipeline_parallel_microbatch_size = 1
expert_parallel_degree = 1
context_parallel_degree = 1
order = ["dp_shard"]

[checkpoint]
enable = false
folder = "checkpoint"
interval = 500
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[compile]
enable = false
components = ["model", "loss"]

[activation_checkpoint]
mode = "selective"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[validation]
enable = false
dataset = "c4_validation"
freq = 500
steps = 1200 # Recommend value for c4_validation with world-size=8 and seq_len=8192

[sweep]
enable = false 
max_width = 1024
eps = 1e-8
param = "ffn_scale"
